### ISSUE TITLE
Why graph connectivity is considered a Batch correction metric?

### ISSUE THREAD

**Issue by johnarevalo** [theislab/scib-pipeline#19]
By reading the description in [[Luecken, 2022]](https://www.nature.com/articles/s41592-021-01336-8) and the [implementation](https://github.com/theislab/scib/blob/main/scib/metrics/graph_connectivity.py#L6), graph connectivity metric only considers biological information (`label_key`).  However, the website and the paper present it as a "batch correction" metric.
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1301626/159368233-6262972f-40c6-4640-abcf-50c2fda7434e.png">

I appreciate your help on figuring out what I am missing here

**Comment by LuckyMD** [comment]
Hi @johnarevalo,

You are correct that graph connectivity only uses label information, and somewhat blurs the line between batch removal and bio conservation. We regard the metric as a batch removal metric as it assesses whether batch effects have been removed in the embedding so that cell identities are connected in the integrated knn graph. This connectivity only assesses whether cells of the same label are close together, but doesn't measure any counterbalance to this from over-correction and removing meaningful biological variation. Also, it represents a very low bar for success, as if batch effects are not very strong (less strong than cell identity separation), then cells with the same label may mostly be connected already in unintegrated data. It does however weed out particularly poorly performing integrations where particular batches are not at all well integrated.

Hope this helps!
